# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/alexswart/s0tool/tree/main/esphome
# © Huizebruin.nl
substitutions:
  name: s0tool-watermeter

esphome:
  name: ${name}
  platform: ESP8266
  board: nodemcuv2
  name_add_mac_suffix: true
  esp8266_restore_from_flash: true
  comment: '${device_description}'
  project:
    name: "huizebruin.${name}"
    version: "${vdate}"

dashboard_import:
  package_import_url: github://alexswart/s0tool/esphome/watermeter.yaml

packages:
  remote_package:
    url: https://github.com/alexswart/s0tool/
    ref: main
    files:
      - esphome/components/basis.yaml
      - esphome/components/watermeter.yaml
    refresh: 0d
